runtime: nodejs18
instance_class: F2
env_variables:
  NODE_ENV: 'production'
handlers:
  - url: /
    static_files: dist/my-angular-app/index.html
    upload: dist/my-angular-app/index.html
  - url: /
    static_dir: dist/my-angular-app
